name: Build and Push Job
description: Build and push Docker image to registry
on:
  workflow_call:
    inputs:
      registry:
        description: 'Docker registry URL'
        required: false
        type: string
        default: 'docker.io'
      image-name:
        description: 'Docker image name'
        required: true
        type: string
      dockerhub-username:
        description: 'Docker Hub username'
        required: true
        type: string
      dockerhub-token:
        description: 'Docker Hub token'
        required: true
        type: string
      dockerfile:
        description: 'Path to Dockerfile'
        required: false
        type: string
        default: './Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker
      uses: ./.github/workflows/steps/setup-docker.yml

    - name: Docker Login
      uses: ./.github/workflows/steps/docker-login.yml
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Build and Push Docker Image
      uses: ./.github/workflows/steps/build-push-docker.yml
      with:
        registry: ${{ inputs.registry }}
        image-name: ${{ inputs.image-name }}
        username: ${{ inputs.dockerhub-username }}
        dockerfile: ${{ inputs.dockerfile }} 