name: Build and Push Docker Image
description: Build and push Docker image to registry
inputs:
  registry:
    description: 'Docker registry URL'
    required: true
    default: 'docker.io'
  image-name:
    description: 'Docker image name'
    required: true
  username:
    description: 'Docker Hub username'
    required: true
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: './Dockerfile'

runs:
  using: composite
  steps:
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.username }}/${{ inputs.image-name }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64 