name: Docker Login
description: Login to Docker Hub
inputs:
  username:
    description: 'Docker Hub username'
    required: true
  password:
    description: 'Docker Hub token'
    required: true

runs:
  using: composite
  steps:
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }} 