name: Setup SSH
description: Setup SSH for server deployment
inputs:
  ssh-private-key:
    description: 'SSH private key for server access'
    required: true

runs:
  using: composite
  steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }} 