name: SonarQube Analysis
description: Run SonarQube analysis on Java code
inputs:
  sonar-token:
    description: 'SonarQube token'
    required: true
  java-version:
    description: 'Java version to use'
    required: false
    default: '17'

runs:
  using: composite
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: maven

    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run SonarQube analysis
      run: mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }} 