name: Deploy Job
on:
  workflow_call:
    inputs:
      image-name:
        description: 'Docker image name'
        required: true
        type: string
      deployment-path:
        description: 'Deployment path on server'
        required: false
        type: string
        default: '/opt/app'
    secrets:
      server-host:
        description: 'Server hostname or IP'
        required: true
      server-user:
        description: 'Server username'
        required: true
      dockerhub-username:
        description: 'Docker Hub username'
        required: true
      ssh-private-key:
        description: 'SSH private key for server access'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: ./.github/workflows/steps/setup-ssh.yml
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      uses: ./.github/workflows/steps/deploy-to-server.yml
      with:
        server-host: ${{ secrets.SERVER_HOST }}
        server-user: ${{ secrets.SERVER_USER }}
        dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
        image-name: ${{ inputs.image-name }}
        deployment-path: ${{ inputs.deployment-path }} 