name: Build and Deploy to DockerHub

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

# Add permissions for security scanning
permissions:
  contents: read
  security-events: write
  actions: read

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  test:
    uses: ./.github/workflows/jobs/test.yml
    with:
      java-version: '17'
      postgres-db: ${{ github.event.repository.name }}_db
      postgres-user: postgres
      postgres-password: password

  build-and-push:
    needs: test
    uses: ./.github/workflows/jobs/build-and-push.yml
    with:
      registry: ${{ env.REGISTRY }}
      image-name: ${{ env.IMAGE_NAME }}
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  sonarqube:
    needs: test
    uses: ./.github/workflows/jobs/sonarqube.yml
    with:
      java-version: '17'
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  deploy:
    needs: build-and-push
    uses: ./.github/workflows/jobs/deploy.yml
    with:
      server-host: ${{ secrets.SERVER_HOST }}
      server-user: ${{ secrets.SERVER_USER }}
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      image-name: ${{ env.IMAGE_NAME }} 